### ISSUE TITLE
Lost my background color after publishing to web

### ISSUE THREAD

**Issue by ROBMS6** [aug-riedinger/google-docs-publisher#13]
I'm new to Google docs and publisher, after generating a google doc and using publisher, the url/web link did not maintain the background color of the original google doc.  Any idea how to correct this?

**Comment by ROBMS6** [comment]
To be more specific, the Page color I set up in my Google Doc is not visible in the web link after publishing.

**Comment by aug-riedinger** [comment]
Hello Rob,
I'll need you to send me a document example if you want me to investigate further.
That said, if it is not in the published version of google docs, it won't be in the google docs publisher, since it is the only data that is available to me.
There is a possibility I'd add some document customization features in the future in a paid plan. Would you be interested into that?

**Comment by aug-riedinger** [comment]
Closing because lack of answer.
