### ISSUE TITLE
Not really an issue - just a Q . . 

### ISSUE THREAD

**Issue by philiprhoades** [aug-riedinger/google-docs-publisher#62]
Augnustin,

I usually don't care much what the published docs look like (it is more important just to get the text out there) but this time I did - I've had gdoc in a tab for ages so I finally tried it out - it was A4 portrait but it worked perfectly! - thanks!

Looks like no code update for some years so I guess nothing has broken for a while?

Regards,
Phil.

**Comment by augnustin** [comment]
Thanks for you interest Phil.

You are correct that the code has not been updated lately in github. The truth is, since I have had issues with malicious documents trying to make some phishing, I've had to add some security checks which I haven't open-sourced to prevent potential hackers from bypassing those. So the most recent code updates don't lie here. 

That said, I'm leaving this repo as a target because:
1. Users should know that the project is open-source
2. If someone wants to self host the projet, they should not be concerned by those security checks hence they won't need it
3. If someone does want to have the *securized* version of the code, I'll be happy to share it privately.

Finally, you are correct that this piece of code is not highly complicated and doesn't require much maintenance anyway.

**Comment by philiprhoades** [comment]
> The truth is, since I have had issues with malicious documents trying to make some phishing, I've had to add some security checks which I haven't open-sourced to prevent potential hackers from bypassing those. So the most recent code updates don't lie here.

Damn . . well that possibility never occurred to me . . bloody nuisances . .

OK, I will have a look at the code and see if I can install it on my own server and see how I go.

BTW, if you can create a little website that creates a page from my GD that is identical to what I see when I edit the doc - why doesn't Google create the same looking doc (by default) when it is published to the web? - it seems stupid not to . . 

Thanks for your work!

**Comment by augnustin** [comment]
> bloody nuisances . .

Yep, sad to have to deal with this kind of issue when you are trying to help people. :disappointed: But I guess that's how the real world goes.

If you want to get your own instance, let me know how it goes. There may have been slight CSS changes I haven't reported there so I could give it to you when I have time.

> BTW, if you can create a little website that creates a page from my GD that is identical to what I see when I edit the doc - why doesn't Google create the same looking doc (by default) when it is published to the web? - it seems stupid not to . .

Good question, that's precisely why I chose this display style.

> Thanks for your work!

Cheers!
