### ISSUE TITLE
RTL Text appear LTR in some sections

### ISSUE THREAD

**Issue by gatigno** [aug-riedinger/google-docs-publisher#7]
Noticed that in tables and in Headers

https://gdoc.pub/1xAu3bRKNBfp1vNBucvD25MpuxnxG9yi_JSPXSVUNuw4

Great Project. Thanks!

**Comment by aug-riedinger** [comment]
Hi @gatigno 
Thanks for submission. Unfortunately there isn't much I can do, since the wrong alignment is also present in the original google docs: https://docs.google.com/document/d/1xAu3bRKNBfp1vNBucvD25MpuxnxG9yi_JSPXSVUNuw4/pub

Looking at the code though, it seems that the problem is not on the table itself but on the `<p>` inside the table element:

```
<p class="c7" dir="rtl"><span class="c6">מניב</span></p>
```

with 

```
.c7 {
    padding-top: 0pt;
    padding-bottom: 0pt;
    line-height: 1.0;
    text-align: left;
}
```

If one removes the `text-align: left;`, it seems to work fine. So keep playing on your document so that the original one gets the correct alignment and it should report to the gdoc.pub one.

Cheers

**Comment by aug-riedinger** [comment]
Closing for now, let me know if you have more troubles on this.
